//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oddzialy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oddzialy()
        {
            this.LekarzOddzial = new HashSet<LekarzOddzial>();
            this.PersonelOddzial = new HashSet<PersonelOddzial>();
        }
    
        public int OddzialId { get; set; }
        public string NazwaOddzialu { get; set; }
        public string Lokalizacja { get; set; }
        public Nullable<System.DateTime> DataOtwarcia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LekarzOddzial> LekarzOddzial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelOddzial> PersonelOddzial { get; set; }
    }
}
