//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelOddzial
    {
        public int PersonelOddzial1 { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> OddzialId { get; set; }
        public Nullable<System.DateTime> DataDolaczenia { get; set; }
    
        public virtual Oddzialy Oddzialy { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
