//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skierowanie
    {
        public int SkierowanieId { get; set; }
        public Nullable<int> BadanieId { get; set; }
        public string NumerSkierowania { get; set; }
        public Nullable<System.DateTime> DataWydania { get; set; }
    
        public virtual Badania Badania { get; set; }
    }
}
