//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towar
    {
        public int IdTowaru { get; set; }
        public string Kod { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> StawkaVatZakupu { get; set; }
        public Nullable<decimal> StawkaVatSprzedazy { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<decimal> Marza { get; set; }
    }
}
