//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyty
    {
        public int WizytaId { get; set; }
        public Nullable<int> PacjentId { get; set; }
        public Nullable<int> LekarzId { get; set; }
        public Nullable<System.DateTime> DataWizyty { get; set; }
    
        public virtual Lekarze Lekarze { get; set; }
        public virtual Pacjenci Pacjenci { get; set; }
    }
}
